### ISSUE TITLE
Add Swagger annotations in 'LIST'

### ISSUE THREAD

**Issue by shihokuni** [nyu-devops-2021-summer-promotions/promotions#125] opened 2021-08-03 01:37 UTC
**As a** user 
**I need** a List all and Query Swagger Docs
**So that**  we can use the API

**Assumptions:** 
* We would use Swagger
* update **list_promotions** under the **PromotionCollection** #126 in the **routes.py**
* add **expect** with **promotopm_args**
* add **marshal_list_with**

**Acceptance Criteria:**
```
Given the /apidocs/
When we try to access GET /promotions in the doc
Then we can see Parameters(promotopm_args) and Responses 200 with response json values

When we send LIST request(Try it out) without any query
Then I can get 200 and see all existing promotions, and the response format is the same as the doc said

When we send LIST request(Try it out) with set existing promotion_type query
Then I can get 200 and see all promotions query by promotion_type, and the response format is the same as the doc said

When we send LIST request(Try it out) with set existing active query
Then I can get 200 and see all promotions query by active, and the response format is the same as the doc said

When we send LIST request(Try it out) with set existing title query
Then I can get 200 and see all promotions query by title, and the response format is the same as the doc said

When we send LIST request(Try it out) with set existing end_date query
Then I can get 200 and see all promotions query by end_date, and the response format is the same as the doc said

When we send LIST request(Try it out) with invalid query (such as 'abc' or year exceed 4 digits) 
Then I would get 400 and see 'Bad request', and the response format is the same as the doc said

Given list_promotions function in PromotionCollection Class
Then swagger annotations exist
```

**Comment by Pmahindra93** [comment] 2021-08-10 16:10
Just checked the code and this seems to be already done? Please confirm if there is something to be added otherwise we should close this issue :)

**Comment by shihokuni** [comment] 2021-08-10 17:17
@jtsen @tcm390 
I think you tried to fix some issues about LIST. And now you fixed it!!
Let's leave our test results in the comment and if ok close the story because `Acceptance criteria` did not cover that error pattern.
Could you add in this comment what request you sent and what code you receive?

**Comment by jtsen** [comment] 2021-08-10 23:57
@shihokuni 
testing from /apidocs, query by title and type I think both work as intended. With weird data we generally just get 200 back with an empty list (which I think is normal for Strings).

As for the problematic query by end date, it currently will not accept any input that is alphabetical, such as "abc" (will not let me execute). As for numeric inputs, anything more than 4 digits will return 400 ("12345') but anything less will return 200 with an empty list. 

Lastly, sequences that deviate from the format YYYY-MM-DD will also cause the application to return a 400 error.

**Closed as completed** 2021-08-11 17:22 UTC
Labels: enhancement
